### ISSUE TITLE
请问一下大佬固件怎么刷

### ISSUE THREAD

**Issue by Zhuangmoumou** [zc360/Xiaomi-ax3000t-openwrt#1]
请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要ssh？

**Comment by zc360** [comment]
先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件

**Comment by zc360** [comment]
> 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要ssh？

先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件

**Comment by Zhuangmoumou** [comment]
> > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要ssh？
> 
> 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件

为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？

**Comment by zc360** [comment]
> > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要ssh？
> > 
> > 
> > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> 
> 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？

你先试一下192.168.1.1能不能登录后台

**Comment by zc360** [comment]
> > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要ssh？
> > 
> > 
> > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> 
> 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？

你看一下READNE，我简单写了个刷入教程

**Comment by Zhuangmoumou** [comment]
> > > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要ssh？
> > > 
> > > 
> > > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> > 
> > 
> > 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？
> 
> 你先试一下192.168.1.1能不能登录后台

当时试了，也改了网关什么的，不能登陆

**Comment by zc360** [comment]
> > > > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要SSH？
> > > > 
> > > > 
> > > > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> > > 
> > > 
> > > 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？
> > 
> > 
> > 你先试一下192.168.1.1能不能登录后台
> 
> 当时试了，也改了网关什么的，不能登陆

访问192.168.1.1浏览器的提示是什么样的，发个截图

**Comment by Zhuangmoumou** [comment]
> > > > > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要SSH？
> > > > > 
> > > > > 
> > > > > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> > > > 
> > > > 
> > > > 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？
> > > 
> > > 
> > > 你先试一下192.168.1.1能不能登录后台
> > 
> > 
> > 当时试了，也改了网关什么的，不能登陆
> 
> 访问192.168.1.1浏览器的提示是什么样的，发个截图
![46E66E99-2D86-459A-8C65-728ED403BC3D](https://github.com/zc360/Xiaomi-ax3000t-openwrt/assets/103405023/4eda6f65-8123-47b8-ba64-e0bf13da9703)

**Comment by Zhuangmoumou** [comment]
> > > > > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要SSH？
> > > > > 
> > > > > 
> > > > > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> > > > 
> > > > 
> > > > 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？
> > > 
> > > 
> > > 你先试一下192.168.1.1能不能登录后台
> > 
> > 
> > 当时试了，也改了网关什么的，不能登陆
> 
> 访问192.168.1.1浏览器的提示是什么样的，发个截图 ![46E66E99-2D86-459A-8C65-728ED403BC3D](https://private-user-images.githubusercontent.com/103405023/302614113-4eda6f65-8123-47b8-ba64-e0bf13da9703.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjA4NjcsIm5iZiI6MTcwNzIyMDU2NywicGF0aCI6Ii8xMDM0MDUwMjMvMzAyNjE0MTEzLTRlZGE2ZjY1LTgxMjMtNDdiOC1iYTY0LWUwYmYxM2RhOTcwMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTE1NjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFjMGViMzVmNzRiOWU0NWI4ZDhlMjJlNzE0ODJmMTRhODA2ZjZiZDQxNjEwNTZkNmUwMzA5ZWFjNjAwMTM2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JukweK0cwJLxtcmgIkTUexPZG6sHTUJ73rNgjzxhb1U)

和这个一样，现在没带电脑，云电脑代替一下，没办法

**Comment by zc360** [comment]
> > > > > > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要SSH？
> > > > > > 
> > > > > > 
> > > > > > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> > > > > 
> > > > > 
> > > > > 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？
> > > > 
> > > > 
> > > > 你先试一下192.168.1.1能不能登录后台
> > > 
> > > 
> > > 当时试了，也改了网关什么的，不能登陆
> > 
> > 
> > 访问192.168.1.1浏览器的提示是什么样的，发个截图
> > ![46E66E99-2D86-459A-8C65-728ED403BC3D](https://private-user-images.githubusercontent.com/103405023/302614113-4eda6f65-8123-47b8-ba64-e0bf13da9703.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjA5MjAsIm5iZiI6MTcwNzIyMDYyMCwicGF0aCI6Ii8xMDM0MDUwMjMvMzAyNjE0MTEzLTRlZGE2ZjY1LTgxMjMtNDdiOC1iYTY0LWUwYmYxM2RhOTcwMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTE1NzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg3Yjg5MTNjYzU3MTg5NzdhOTE3YzA5NjQyMDE5ZWU3MzdkOWNmY2I3MDgwOGQ5NTg2ZTJmOTNjZDU0MmJkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vlRpUsyv35eJDSDmigL5Ko5cId6zWW1kLzAwuS-3AlY)

看一下你的以太网设置ipv4

**Comment by zc360** [comment]
> > > > > > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要SSH？
> > > > > > 
> > > > > > 
> > > > > > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> > > > > 
> > > > > 
> > > > > 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？
> > > > 
> > > > 
> > > > 你先试一下192.168.1.1能不能登录后台
> > > 
> > > 
> > > 当时试了，也改了网关什么的，不能登陆
> > 
> > 
> > 访问192.168.1.1浏览器的提示是什么样的，发个截图![46E66E99-2D86-459A-8C65-728ED403BC3D](https://private-user-images.githubusercontent.com/103405023/302614113-4eda6f65-8123-47b8-ba64-e0bf13da9703.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjA4NjcsIm5iZiI6MTcwNzIyMDU2NywicGF0aCI6Ii8xMDM0MDUwMjMvMzAyNjE0MTEzLTRlZGE2ZjY1LTgxMjMtNDdiOC1iYTY0LWUwYmYxM2RhOTcwMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTE1NjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFjMGViMzVmNzRiOWU0NWI4ZDhlMjJlNzE0ODJmMTRhODA2ZjZiZDQxNjEwNTZkNmUwMzA5ZWFjNjAwMTM2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JukweK0cwJLxtcmgIkTUexPZG6sHTUJ73rNgjzxhb1U)
> 
> 和这个一样，现在没带电脑，云电脑代替一下，没办法

你是用网线直接连接的路由器吗

**Comment by Zhuangmoumou** [comment]
是的但是不记得是不是lan1了

**Comment by Zhuangmoumou** [comment]
> > > > > > > > 请问一下大佬，这个固件是直接就在192.168.31.1那边直接刷还是要SSH？
> > > > > > > 
> > > > > > > 
> > > > > > > 先开ssh（网上有教程）再在ssh里刷uboot，然后再在uboot里刷固件
> > > > > > 
> > > > > > 
> > > > > > 为什么我刷了uboot之后断电按网上那些写些教程按reset再通电直接很快从红灯跳到蓝灯，没有黄灯？
> > > > > 
> > > > > 
> > > > > 你先试一下192.168.1.1能不能登录后台
> > > > 
> > > > 
> > > > 当时试了，也改了网关什么的，不能登陆
> > > 
> > > 
> > > 访问192.168.1.1浏览器的提示是什么样的，发个截图![46E66E99-2D86-459A-8C65-728ED403BC3D](https://private-user-images.githubusercontent.com/103405023/302614113-4eda6f65-8123-47b8-ba64-e0bf13da9703.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjA4NjcsIm5iZiI6MTcwNzIyMDU2NywicGF0aCI6Ii8xMDM0MDUwMjMvMzAyNjE0MTEzLTRlZGE2ZjY1LTgxMjMtNDdiOC1iYTY0LWUwYmYxM2RhOTcwMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTE1NjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFjMGViMzVmNzRiOWU0NWI4ZDhlMjJlNzE0ODJmMTRhODA2ZjZiZDQxNjEwNTZkNmUwMzA5ZWFjNjAwMTM2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JukweK0cwJLxtcmgIkTUexPZG6sHTUJ73rNgjzxhb1U)
> > 
> > 
> > 和这个一样，现在没带电脑，云电脑代替一下，没办法
> 
> 你是用网线直接连接的路由器吗

是的但是不记得是不是lan1了

**Comment by zc360** [comment]
> 是的，但是不记得是不是lan1了

一定要连第一个网口

**Comment by Zhuangmoumou** [comment]
> > 是的，但是不记得是不是lan1了
> 
> 一定要连第一个网口

等我回头再试一次好吧

**Comment by zc360** [comment]
你试一下路由器断电再用针按住 reset 不放，再接上电源，等待 10s 左右松开

**Comment by zc360** [comment]
然后再打开192.168.1.1

**Comment by Zhuangmoumou** [comment]
好

**Comment by zc360** [comment]
你可能没有按reser导致没有进uboot

**Comment by zc360** [comment]
https://wwk.lanzouo.com/iL71O1nk1p3e

**Comment by zc360** [comment]
用这个，每个设备的uboot都不一样

**Comment by zc360** [comment]
你照着我的README操作应该就没什么问题了

**Comment by Zhuangmoumou** [comment]
> 你照着我的README操作应该就没什么问题
ok

**Comment by Zhuangmoumou** [comment]
> 你照着我的README操作应该就没什么问题了

但是这个路由器不是4个lanwan口通用的吗？

**Comment by zc360** [comment]
> > 你照着我的README操作应该就没什么问题了
> 
> 但是这个路由器不是4个lanwan口通用的吗？

通用功能是小米固件支持的，刷了其他固件后这个功能就没了，wan lan要分

**Comment by zc360** [comment]
如果问题解决了将关闭此Issues
