### ISSUE TITLE
我现在有一个新的openwrt固件，要怎么重新进到uboot？

### ISSUE THREAD

**Issue by Zhuangmoumou** [zc360/Xiaomi-ax3000t-openwrt#2]

**Comment by Zhuangmoumou** [comment]
不用了我装好了

**Comment by Zhuangmoumou** [comment]
这个版本是23.11.11的，我觉得更好看https://pan.baidu.com/s/11dojC6Gp0DEhgROcybP1Og?pwd=ywnz

**Comment by Zhuangmoumou** [comment]
还有更多功能

**Comment by zc360** [comment]
> 这个版本是23.11.11的，我觉得更好看 https://pan.baidu.com/s/11dojC6Gp0DEhgROcybP1Og?pwd=ywnz

我这个固件内置的主题是旧版的，可以下新版的argon主题手动升级https://github.com/jerrykuku/luci-theme-argon
