### ISSUE TITLE
5G检测不到

### ISSUE THREAD

**Issue by Zhuangmoumou** [zc360/Xiaomi-ax3000t-openwrt#4]
![Uploading Screenshot_20240214_100953_com.microsoft.emmx.jpg…]()
最近5G无线设备一直都检测不到，然后看了一下设置5G变成了6G？

**Comment by Zhuangmoumou** [comment]
![Uploading Screenshot_20240214_100953_com.microsoft.emmx_edit_619100575624800.jpg…]()

**Comment by zc360** [comment]
我是能正常使用5.2g的，手机电脑都可以，电视收不到信号（电视不支持wifi6），下面是我的路由器5.2g信号配置
<img width="810" alt="屏幕截图 2024-02-15 014738" src="https://github.com/zc360/Xiaomi-ax3000t-openwrt/assets/83486674/1d1fcb72-ebe4-45ec-b756-9593189d9abd">

**Comment by Zhuangmoumou** [comment]
> 我是能正常使用5.2g的，手机电脑都可以，电视收不到信号（电视不支持wifi6），下面是我的路由器5.2g信号配置 <img alt="屏幕截图 2024-02-15 014738" width="810" src="https://private-user-images.githubusercontent.com/83486674/304827854-1d1fcb72-ebe4-45ec-b756-9593189d9abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NjEyMzAsIm5iZiI6MTcwNzk2MDkzMCwicGF0aCI6Ii84MzQ4NjY3NC8zMDQ4Mjc4NTQtMWQxZmNiNzItZWJlNC00NWVjLWI3NTYtOTU5MzE4OWQ5YWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDAxMzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTU4NWYxMTY4ZWNjM2JjNDk2ZjMyZjlmZDZiN2RlMjNkMDBhOTE2M2I2YTFlOGJiYTUxMDQxNDE3MDExNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ru_bd87OT0QatvI44Xg0c-PTDIEfp3ZgxqLjpA3YYxo">

我现在要怎么刷回原厂？我现在连后台都打不开了，WiFi没网
