### ISSUE TITLE
ShadowSocksR Plus无法正常使用

### ISSUE THREAD

**Issue by Heipen** [zc360/Xiaomi-ax3000t-openwrt#8]
大佬麻烦看一下，我装好以后ssr plus一直在运行中和未运行反复横跳，然后谷歌连通性测试从来没通过。。。
![image](https://github.com/user-attachments/assets/89495b50-3f86-4b4f-819e-78c11f6fd62a)

然后还有一点问题我不明白，我在软件包里装的OpenVPN不能用，点添加配置就给我报这个。。。
/usr/lib/lua/luci/dispatcher.lua:482: Failed to execute cbi dispatcher target for entry '/admin/services/openvpn'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/openvpn.lua:64: bad argument #4 to 'set' (string expected, got boolean)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:482: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

**Comment by zc360** [comment]
我也不清楚ssr反复横跳具体是什么问题导致的，我自己用的很好，我只有一个节点，你可能是有多个节点开了自动切换节点导致的，你ssr的设置都是默认的吗

**Comment by Heipen** [comment]
我查了下日志发现和这个问题是一样的https://github.com/fw876/helloworld/issues/1331，但是我不会自行编译所以无法检查我是否也是md5的问题

**Comment by Heipen** [comment]
我之前刷过这个固件https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8307467&highlight=3000T ，ssr是可以正常用的，但这个固件的DDNS几乎没法用。。。

**Comment by zc360** [comment]
我觉得应该是你节点的问题，我自己用得没有问题
